### ISSUE TITLE
херь с компиляцией

### ISSUE THREAD

**Issue by k-payl** [DGLE-HQ/DWinDirect#1]
Решил ради спортивного интереса скомпилить dx11 и потестить раз уже все готово. В файле CoreRendererDX11.cpp вылезло миллион ошибок. Например D3DDECLTYPE_D3DCOLOR не определено, ну или на 267 строке явно скобок не хватает:
        if (_indicesCount) != bool(uiIndicesCount))
            return E_INVALIDARG;
Так версия под dx11 не готова или это я туплю?:D

**Comment by ash3D** [comment]
DX11 в движке присутствует в двух вариантах: CoreRendererDX11 и экспериментальный render prototype (отдельный solution в этом же репозитории).
CoreRenderer полностью готов для DX9, можно пробовать и тестировать. Надо только не забыть в папку dgle скопировать хедеры из основного репозитория. DX11 разрабатывается на основе DX9 и на данный момент представляет из себя смесь из DX9 кода, который постепенно заменяется на DX11, поэтому сейчас не компилируется.
Работающий DX11 есть в render prototype. Это высокоуровневый рендер (в отличие от низкоуровневого CoreRenderer), сейчас там реализованы 2D сцены со статическими и динамическими объектами и immediate mode с батчингом.

**Comment by k-payl** [comment]
Рендер DX9 скомпилился, заработало, прикольно) Только при переходе из маленького окна к большому, все ужасно растягивается. В render prototype тоже что то скомпилировалось, в итоге появился белый вращающийся квадратик на черном фоне. В render prototype посмотрел файлик Iterface/Renderer.h - если честно офигел, похоже затевается что то грандиозное)) Если я правильно понял, HightLevel должен заменить существующие Render3D, Render2D.

**Comment by ash3D** [comment]
Причины растягивания понятны, надо будет поправить.
Квадратик в render protitype - один из тестов. В "render prototype.cpp" есть и другие закомментированные тесты, в основном для оценки производительности.
HightLevel не заменяет Render3D и Render2D, а предлагает наиболее оптимизированные реализации конкретных задач. Render3D/2D более низкоуровневый и позволяет явно задавать стейты, что, с одной стороны, обеспечивает большую гибкость, с другой - требует от пользователя больше действий для достижения результата и предотвращает многие глобальные оптимизации.
